server:
  port: 8081
  

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: OtherService


resilience4j.ratelimiter:
  instances:
    SimpleService:
      limitForPeriod: 5
      limitRefreshPeriod: 5s
      timeoutDuration: 0s