server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: CustomerService

resilience4j.ratelimiter:
  instances:
    AccountService:
        limitForPeriod: 5
        limitRefreshPeriod: 5s
        timeoutDuration: 0s
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
    
  endpoint:
    health:
      show-details: always